workspace:
  base: /go
  path: src/github.com/kreativka/gostempel

pipeline:
  deps:
    image: ${GO_VERSION}
    commands:
      - go get
  test:
    image: ${GO_VERSION}
    commands:
      - go test -test.v github.com/kreativka/gostempel/javautf
      - go test -test.v github.com/kreativka/gostempel/egothor
      - go test -test.v
  benchmark:
    image: ${GO_VERSION}
    commands:
      - go test -bench=. -benchmem

matrix:
  GO_VERSION:
    - golang:1.8
    - golang:1.9
    - golang:1.10
