kind: pipeline
name: default

steps:
  - name: deps
    image: golang
    pull: allways
    commands:
    - go get
  - name: test
    image: golang
    pull: allways
    commands:
    - go test -test.v ./...
  - name: benchmark
    image: golang
    pull: allways
    commands:
    - go test -bench=. -benchmem
